### ISSUE TITLE
Facedancer --suggest mode doesn't print suggestions, as Ctrl-C is no longer caught

### ISSUE THREAD

**Issue by miek** [greatscottgadgets/facedancer#118]
When running facedancer examples with the `--suggest` argument, pressing Ctrl-C to end the script just prints a backtrace instead of printing the aggregated suggestions. It used to catch the exception, but that got removed in https://github.com/greatscottgadgets/facedancer/pull/92

**Comment by mossmann** [comment]
@kauwua Do you have any objection to reverting ea8c2a6?

**Comment by antoinevg** [comment]
How about:

https://github.com/greatscottgadgets/facedancer/pull/119

**Comment by kauwua** [comment]
catching `KeyboardInterrupt` would be ok in `default_main` since it's a convenience function (the main issue was Facedancer catching Ctrl-C directly in the core library and not exiting). this way you could print the suggestions, exit cleanly (with `exit` probably) to remove the ugly backtrace and users could create their own `main` if they want.

https://github.com/greatscottgadgets/facedancer/pull/119 PR works for me as well

**Comment by miek** [comment]
I'm reluctant to introduce a new keyboard shortcut if we don't need to, I like the suggestion of catching `KeyboardInterrupt` in `default_main` instead.

**Comment by mossmann** [comment]
@antoinevg plans to rework #119 so that the interrupt is caught in `default_main` and the `ctrl-e` solution is moved to an example.

**Comment by antoinevg** [comment]
PR updated, feedback appreciated plz! #119
